const fallbackImages = {
  football: "/projects/project 1/Hero.webp",
  campus: "/projects/project 2/Hero.webp",
  facility: "/projects/project 6/Hero.webp",
  baseball: "/uploads/images/tba-1782384915797.webp",
  soccer: "/uploads/images/tnb-1782385010620.jpg",
  apparel: "/projects/project 1/16.webp",
  guidelines: "/uploads/images/chatgpt-image-jun-26-2026-03-08-57-am-1782414576289.webp",
  patch: "/uploads/images/skets-1782412831183.webp",
  arena: "/projects/project 4/hero.webp",
};

const sectionCopy = {
  overview: "A complete identity system designed to give the program a stronger and more recognizable presence.",
  challenge: "The program needed a visual language that could work across teams, apparel, facilities, and digital platforms without losing consistency.",
  solution: "We developed a focused identity system with a strong primary mark, supporting applications, and a clear visual language.",
  system: "The identity extends across logo usage, apparel, signage, print, social media, and environmental touchpoints.",
  applications: "The system was designed to perform across jerseys, patches, signage, locker rooms, merchandise, and brand guidelines.",
  results: "A unified identity system built to feel recognizable, durable, and ready for real-world use.",
};

export const defaultSiteContent = {
  studioName: "ATHAYA DESIGNED",
  studioSublabel: "Independent Sports Identity Practice",
  primaryCtaLabel: "BOOK A DISCOVERY CALL",
  primaryCtaUrl: "https://calendly.com/athayadzn/30min",
  bookingUrl: "https://calendly.com/athayadzn/30min",
  email: "hello@athayadesigned.com",
  instagramUrl: "#",
  linkedinUrl: "#",
  behanceUrl: "#",
  footerCopyright: "(c) {year} ATHAYA DESIGNED. All rights reserved.",
  logoHorizontalPath: "/assets/athaya-horizontal.png",
  brandmarkPath: "/assets/athaya-brandmark.png",
  defaultOgImagePath: "/assets/athaya-brandmark.png",
  globalBackgroundImagePath: "",
  themeModeNote: "Dark editorial identity system.",
  overlayMenuLinks: [
    { label: "Work", url: "/work", order: 1, enabled: true },
    { label: "Fonts", url: "/fonts", order: 2, enabled: true },
    { label: "About", url: "/about", order: 3, enabled: true },
    { label: "Services", url: "/services", order: 4, enabled: true },
    { label: "Contact", url: "/contact", order: 5, enabled: true },
  ],
  lastSavedAt: "",
};

export const defaultWorks = [
  {
    slug: "panthers-football",
    title: "Panthers Football",
    category: "Complete Identity System",
    year: "2026",
    summary: "A harder, more disciplined football identity built for sideline presence and fanwear.",
    description: "Panthers Football received a complete identity system built around a sharper field presence, stronger apparel language, and a flexible set of marks for game-day communications.",
    services: ["Mascot Mark", "Uniform System", "Apparel", "Brand Guidelines"],
    tags: ["Athletic Identity", "Apparel"],
    coverImage: fallbackImages.football,
    heroImage: fallbackImages.football,
    backgroundImage: "",
    gallery: [fallbackImages.apparel, fallbackImages.patch, fallbackImages.facility, fallbackImages.guidelines],
    featured: true,
    published: true,
    order: 1,
    stats: [
      { label: "Team Touchpoints", value: "24" },
      { label: "Applications", value: "100+" },
      { label: "Unified Identity", value: "1" },
    ],
    sections: sectionCopy,
  },
  {
    slug: "westhaven-university",
    title: "Westhaven University",
    category: "Complete Athletic Identity",
    year: "2026",
    summary: "A university-wide athletic identity system made to unify tradition, teams, and facilities.",
    description: "A complete athletic identity that brings 17 varsity programs under a clear, durable visual system for recruiting, apparel, facilities, and broadcast moments.",
    services: ["Athletic Identity", "Brand System", "Environmental", "Guidelines"],
    tags: ["School Branding", "Brand Systems"],
    coverImage: fallbackImages.campus,
    heroImage: fallbackImages.campus,
    backgroundImage: "",
    gallery: [fallbackImages.guidelines, fallbackImages.facility, fallbackImages.football, fallbackImages.arena],
    featured: true,
    published: true,
    order: 2,
    stats: [
      { label: "Varsity Sports", value: "17" },
      { label: "Applications", value: "100+" },
      { label: "Unified Identity", value: "1" },
    ],
    sections: sectionCopy,
  },
  {
    slug: "westridge-athletics",
    title: "Westridge Athletics",
    category: "School Branding / Environmental",
    year: "2025",
    summary: "A school athletics system extended into facility graphics, signage, and team spaces.",
    description: "Westridge Athletics needed a school identity that could move beyond the logo and shape the physical experience of its athletic facilities.",
    services: ["School Branding", "Environmental Graphics", "Signage", "Apparel"],
    tags: ["School Branding", "Signage"],
    coverImage: fallbackImages.facility,
    heroImage: fallbackImages.facility,
    backgroundImage: "",
    gallery: [fallbackImages.arena, fallbackImages.guidelines, fallbackImages.apparel, fallbackImages.patch],
    featured: false,
    published: true,
    order: 3,
    stats: [
      { label: "Facility Zones", value: "8" },
      { label: "Signage Assets", value: "42" },
      { label: "School System", value: "1" },
    ],
    sections: sectionCopy,
  },
  {
    slug: "cardinals-baseball",
    title: "Cardinals Baseball",
    category: "Athletic Identity",
    year: "2025",
    summary: "A baseball identity refresh focused on patches, uniforms, and ballpark-ready details.",
    description: "Cardinals Baseball was refreshed with a confident team identity that could live naturally on caps, jerseys, patches, dugout signage, and merchandise.",
    services: ["Team Identity", "Patch System", "Uniforms", "Merchandise"],
    tags: ["Athletic Identity", "Mascot Marks"],
    coverImage: fallbackImages.baseball,
    heroImage: fallbackImages.baseball,
    backgroundImage: "",
    gallery: [fallbackImages.patch, fallbackImages.guidelines, fallbackImages.apparel, fallbackImages.arena],
    featured: false,
    published: true,
    order: 4,
    stats: [],
    sections: sectionCopy,
  },
  {
    slug: "united-fc",
    title: "United FC",
    category: "Brand Identity / Merchandise",
    year: "2025",
    summary: "A club identity and merchandise system designed for matchday, retail, and supporters.",
    description: "United FC received a crest-led identity with a practical kit and merchandise language built for matchday energy and long-term recognition.",
    services: ["Crest Design", "Kit System", "Merchandise", "Social Templates"],
    tags: ["Brand Systems", "Apparel"],
    coverImage: fallbackImages.soccer,
    heroImage: fallbackImages.soccer,
    backgroundImage: "",
    gallery: [fallbackImages.apparel, fallbackImages.patch, fallbackImages.facility, fallbackImages.guidelines],
    featured: false,
    published: true,
    order: 5,
    stats: [],
    sections: sectionCopy,
  },
  {
    slug: "ironwood-high-school",
    title: "Ironwood High School",
    category: "School Branding / Environmental",
    year: "2025",
    summary: "A high school athletics identity made for corridors, locker rooms, apparel, and pride.",
    description: "Ironwood High School needed a cohesive athletics presence that could bring consistency to teams, signage, social graphics, and physical spaces.",
    services: ["School Branding", "Mascot System", "Facility Graphics", "Apparel"],
    tags: ["School Branding", "Mascot Marks"],
    coverImage: fallbackImages.arena,
    heroImage: fallbackImages.arena,
    backgroundImage: "",
    gallery: [fallbackImages.facility, fallbackImages.apparel, fallbackImages.guidelines, fallbackImages.patch],
    featured: false,
    published: true,
    order: 6,
    stats: [],
    sections: sectionCopy,
  },
  {
    slug: "northridge-athletics",
    title: "Northridge Athletics",
    category: "Athletic Identity System",
    year: "2026",
    summary: "A complete athletic department system designed for recognition across every sport.",
    description: "Northridge Athletics was built as a flexible department-wide identity system, giving every program a shared visual language without flattening its competitive edge.",
    services: ["Athletic Identity", "Brand Guidelines", "Apparel System", "Signage"],
    tags: ["Athletic Identity", "Brand Systems"],
    coverImage: fallbackImages.guidelines,
    heroImage: fallbackImages.guidelines,
    backgroundImage: "",
    gallery: [fallbackImages.football, fallbackImages.facility, fallbackImages.apparel, fallbackImages.patch],
    featured: true,
    published: true,
    order: 7,
    stats: [
      { label: "Core Lockups", value: "12" },
      { label: "Sport Kits", value: "19" },
      { label: "Launch Season", value: "2026" },
    ],
    sections: sectionCopy,
  },
];

export const defaultFonts = [
  {
    name: "Ironline Display",
    slug: "ironline-display",
    category: "Athletic Display Typeface",
    shortDescription: "A hard-edged display face built for confident marks, apparel drops, and program identity systems.",
    description: "Ironline Display is shaped for athletic identities that need weight, pace, and a strong first read.",
    longDescription: "Built for mascot lockups, oversized apparel graphics, stadium language, and headline systems where presence matters.",
    priceLabel: "From $19",
    payhipUrl: "https://payhip.com/athayadesigned",
    previewText: "BUILT FOR PRESENCE",
    featuredWords: ["PANTHERS", "WILDCATS", "CARDINALS", "IRONWOOD"],
    useCases: ["Athletic identities", "Team apparel", "Mascot lockups", "Campaign headlines"],
    fontFileUrl: "",
    previewImage: "/assets/athaya-brandmark.png",
    specimenImage: "/assets/athaya-brandmark.png",
    backgroundImage: "",
    published: true,
    order: 1,
  },
  {
    name: "Varsity Forge",
    slug: "varsity-forge",
    category: "Sports Lettering Font",
    shortDescription: "A sturdy sports lettering system with varsity rhythm, built for teams and school spirit graphics.",
    description: "Varsity Forge brings a crafted athletic voice to team branding, campus merchandise, and matchday graphics.",
    longDescription: "It has a strong collegiate character while staying flexible enough for modern identity work.",
    priceLabel: "From $19",
    payhipUrl: "https://payhip.com/athayadesigned",
    previewText: "GAME DAY IDENTITY",
    featuredWords: ["NORTHRIDGE", "WESTHAVEN", "UNITED FC", "ATHLETICS"],
    useCases: ["School branding", "Jersey typography", "Fanwear graphics", "Event posters"],
    fontFileUrl: "",
    previewImage: "/assets/athaya-brandmark.png",
    specimenImage: "/assets/athaya-brandmark.png",
    backgroundImage: "",
    published: true,
    order: 2,
  },
  {
    name: "Draco",
    slug: "draco",
    category: "Racing Display Typeface",
    shortDescription: "A sharp racing display font built for speed, motorsport graphics, aggressive logos, and high-impact headlines.",
    description: "Draco is a racing display typeface shaped for fast visual impact, with aerodynamic forms that feel built for motion.",
    longDescription: "Made for motorsport identities, racing posters, apparel graphics, decals, and bold headline systems that need speed, edge, and instant attitude.",
    priceLabel: "From $19",
    payhipUrl: "https://payhip.com/athayadesigned",
    previewText: "SIDELINE ENERGY",
    featuredWords: ["GRIDLINE", "PIT CREW", "OVERDRIVE", "CHECKERED"],
    useCases: ["Racing logos", "Motorsport posters", "Vehicle decals", "Apparel headlines"],
    fontFileUrl: "",
    previewImage: "/assets/athaya-brandmark.png",
    specimenImage: "/assets/athaya-brandmark.png",
    backgroundImage: "",
    published: true,
    order: 3,
  },
  {
    name: "Malibu Sunrise",
    slug: "malibusunrise",
    category: "Nostalgic Display Typeface",
    shortDescription: "A nostalgic display font with a sunlit Miami feel, made for retro branding, apparel, posters, and lifestyle visuals.",
    description: "Malibu Sunrise brings a warm retro voice inspired by coastal nostalgia, pastel-era graphics, and laid-back Miami energy.",
    longDescription: "Built for vintage-inspired identities, resort graphics, summer merch, music artwork, and lifestyle campaigns that need a breezy throwback mood.",
    priceLabel: "From $19",
    payhipUrl: "https://payhip.com/athayadesigned",
    previewText: "CHARACTER FIRST",
    featuredWords: ["OCEAN AVENUE", "SUNSET CLUB", "PALM DRIVE", "COASTLINE"],
    useCases: ["Retro branding", "Summer apparel", "Music artwork", "Lifestyle posters"],
    fontFileUrl: "",
    previewImage: "/assets/athaya-brandmark.png",
    specimenImage: "/assets/athaya-brandmark.png",
    backgroundImage: "",
    published: true,
    order: 4,
  },
];

export const defaultServicesContent = {
  hero: {
    pageLabel: "Services",
    headline: "Identity Design Services",
    supportingCopy: "Premium identity design services for teams, schools, clubs, creators, and brands, including mascot logo design, athletic identity systems, school branding, lettermarks, apparel applications, and brand guidelines.",
    backgroundImage: "",
    ctaLabel: "Start a Project",
    ctaUrl: "/contact",
  },
  items: [
    { number: "01", title: "Identity Marks", slug: "identity-marks", shortDescription: "Logos, monograms, wordmarks, and brandmarks designed with character, clarity, and long-term use in mind.", longDescription: "Primary marks, secondary lockups, black-and-white versions, color versions, and export-ready assets for teams, schools, communities, and brands that need a distinctive identity mark built for real use.", includedItems: ["Primary mark", "Secondary lockup", "Export files"], backgroundImage: "", featured: true, enabled: true, order: 1 },
    { number: "02", title: "Wordmarks & Brandmarks", slug: "wordmarks-brandmarks", shortDescription: "Custom wordmarks, letterforms, and compact brand symbols built for strong recognition across identity systems.", longDescription: "Distinctive wordmarks, brandmarks, lettermarks, monograms, alternate lockups, spacing logic, and export-ready artwork for brands that need a clear verbal and visual signature across digital, apparel, print, and environmental use.", includedItems: ["Custom wordmark", "Brandmark system", "Lockup variations"], backgroundImage: "", featured: true, enabled: true, order: 2 },
    { number: "03", title: "Mascot & Character Identities", slug: "mascot-character-identities", shortDescription: "Character-driven marks for teams, creators, communities, and brands that need a stronger visual presence.", longDescription: "Mascot logos, character marks, typography lockups, avatar versions, color systems, and apparel or social previews shaped for recognition at every scale.", includedItems: ["Mascot mark", "Typography lockup", "Application preview"], backgroundImage: "", featured: true, enabled: true, order: 3 },
    { number: "04", title: "Athletic & School Branding", slug: "athletic-school-branding", shortDescription: "Identity systems for teams, schools, clubs, academies, and athletic programs built for recognition, consistency, apparel, signage, and school spirit.", longDescription: "Athletic branding and school branding systems that can include team marks, institutional marks, wordmarks, monograms, color direction, typography, apparel concepts, signage ideas, and rollout assets.", includedItems: ["Logo system", "Color and type direction", "Application mockups"], backgroundImage: "", featured: false, enabled: true, order: 4 },
    { number: "05", title: "Brand Strategies", slug: "brand-strategies", shortDescription: "Strategic direction for positioning, visual tone, audience clarity, and identity decisions before design production begins.", longDescription: "A focused strategy phase that can define brand positioning, audience context, creative direction, naming or messaging cues, visual references, identity opportunities, and practical rollout priorities so the final design system has a clear foundation.", includedItems: ["Positioning direction", "Visual strategy", "Rollout priorities"], backgroundImage: "", featured: false, enabled: true, order: 5 },
    { number: "06", title: "Brand Guidelines", slug: "brand-guidelines", shortDescription: "Practical identity guides that keep logos, colors, typography, and applications consistent after delivery.", longDescription: "Clear brand guidelines for logo usage, clearspace, incorrect usage, color codes, typography, file handling, apparel applications, and examples for teams, vendors, and collaborators.", includedItems: ["Logo usage", "Color and type rules", "Application examples"], backgroundImage: "", featured: false, enabled: true, order: 6 },
  ],
  processTeaser: {
    sectionLabel: "From Mark To System",
    headline: "A clear process for identity work that needs to last.",
    steps: [
      { number: "01", title: "Discover", description: "Brief, context, goals, and constraints.", imageLabel: "Brief", imagePath: "", order: 1 },
      { number: "02", title: "Design", description: "Concepts, refinement, and identity direction.", imageLabel: "Sketch", imagePath: "", order: 2 },
      { number: "03", title: "Apply", description: "Translate the identity across real use cases.", imageLabel: "System", imagePath: "", order: 3 },
      { number: "04", title: "Deliver", description: "Prepare files and guidance for rollout.", imageLabel: "Rollout", imagePath: "", order: 4 },
    ],
  },
};

export const defaultHomeContent = {
  heroFeaturedProjects: [
    { number: "01", title: "Panthers Football", category: "Featured Project", year: "2026", slug: "panthers-football", description: "Mascot / Apparel / Sideline", image: fallbackImages.football, coverPath: fallbackImages.football, enabled: true, order: 1, accentColor: "#8d2424", heroImages: { center: fallbackImages.football } },
    { number: "02", title: "Westhaven University", category: "Campus Athletics", year: "2026", slug: "westhaven-university", description: "Identity / Stadium / Tradition", image: fallbackImages.campus, coverPath: fallbackImages.campus, enabled: true, order: 2, accentColor: "#8d2424" },
    { number: "03", title: "Ironridge Athletics", category: "Team System", year: "2025", slug: "ironwood-high-school", description: "Mascot / Jersey / Fanwear", image: fallbackImages.apparel, coverPath: fallbackImages.apparel, enabled: true, order: 3, accentColor: "#8d2424" },
    { number: "04", title: "Cardinals Baseball", category: "Club Refresh", year: "2025", slug: "cardinals-baseball", description: "Patch / Uniform / Ballpark", image: fallbackImages.baseball, coverPath: fallbackImages.baseball, enabled: true, order: 4, accentColor: "#8d2424" },
    { number: "05", title: "United FC", category: "Football Club", year: "2025", slug: "united-fc", description: "Crest / Kit / Matchday", image: fallbackImages.soccer, coverPath: fallbackImages.soccer, enabled: true, order: 5, accentColor: "#8d2424" },
    { number: "06", title: "Northridge Athletics", category: "Athletic Department", year: "2026", slug: "northridge-athletics", description: "Guidelines / Apparel / Signage", image: fallbackImages.guidelines, coverPath: fallbackImages.guidelines, enabled: true, order: 6, accentColor: "#8d2424" },
    { number: "07", title: "Westridge Athletics", category: "School Athletics", year: "2025", slug: "westridge-athletics", description: "Facilities / Signage / Team Spaces", image: fallbackImages.facility, coverPath: fallbackImages.facility, enabled: true, order: 7, accentColor: "#8d2424" },
  ],
  headline: {
    line1: "Identity Marks With Character,",
    line2: "Craft, And Presence.",
    supportingParagraph: "Athaya Designed crafts distinctive logos, mascot identities, and visual systems for teams, schools, communities, and brands that need to look established, recognizable, and built to last.",
    primaryCtaLabel: "Start a Project",
    primaryCtaUrl: "/contact",
    secondaryCtaLabel: "View Selected Work",
    secondaryCtaUrl: "/work",
  },
  whatWeDo: {
    items: ["Identity Marks", "Wordmarks & Brandmarks", "Mascot & Character Identities", "Athletic & School Branding", "Brand Strategies", "Brand Guidelines"].map((label, index) => ({ label, enabled: true, order: index + 1 })),
  },
  featuredCaseStudy: {
    selectedWorkSlug: "westhaven-university",
    title: "Westhaven University",
    category: "Complete Athletic Identity",
    paragraph: "A comprehensive identity system built to unify 17 varsity sports under one powerful brand.",
    stats: [
      { value: "17", label: "Varsity Sports" },
      { value: "100+", label: "Applications" },
      { value: "1", label: "Unified Identity" },
    ],
    chapters: [
      { number: "01", title: "Overview", label: "Featured Case Study", heading: "Westhaven University", category: "Complete Athletic Identity", paragraph: "A comprehensive identity system built to unify 17 varsity sports under one powerful brand. Rooted in tradition. Built for the future.", stats: [{ value: "17", label: "Varsity Sports" }, { value: "100+", label: "Applications" }, { value: "1", label: "Unified Identity" }], images: [{ type: "jersey", label: "WESTHAVEN", detail: "24" }, { type: "flag", label: "W" }, { type: "wall", label: "TRADITION BUILT HERE" }, { type: "book", label: "ATHLETIC IDENTITY GUIDE" }] },
      { number: "02", title: "Challenge", label: "Featured Case Study", heading: "Westhaven University", category: "Challenge / Fragmented Team Language", paragraph: "Westhaven had recognition, but its sports looked disconnected across uniforms, facilities, recruiting, and printed touchpoints.", stats: [{ value: "6", label: "Marks Reviewed" }, { value: "17", label: "Teams Audited" }, { value: "42", label: "Use Cases Mapped" }], images: [{ type: "patch", label: "Legacy Marks" }, { type: "wall", label: "MIXED SIGNALS" }, { type: "book", label: "AUDIT / APPLICATIONS" }, { type: "flag", label: "W" }] },
      { number: "03", title: "Solution", label: "Featured Case Study", heading: "Westhaven University", category: "Solution / One Mark With Game-Day Weight", paragraph: "The new system sharpened the crest, tightened the wordmark, and created a high-contrast visual language for every athletic moment.", stats: [{ value: "1", label: "Primary Crest" }, { value: "3", label: "Wordmark Tiers" }, { value: "8", label: "Core Lockups" }], images: [{ type: "flag", label: "W" }, { type: "jersey", label: "WESTHAVEN", detail: "24" }, { type: "patch", label: "PRIMARY CREST" }, { type: "book", label: "LOCKUP SYSTEM" }] },
      { number: "04", title: "The System", label: "Featured Case Study", heading: "Westhaven University", category: "The System / Rules For Every Touchpoint", paragraph: "The identity was translated into a repeatable toolkit for apparel, signage, social, print, recruiting, and sport-specific extensions.", stats: [{ value: "12", label: "Core Rules" }, { value: "4", label: "Color Roles" }, { value: "30+", label: "Templates" }], images: [{ type: "book", label: "BRAND BOOK / SYSTEM" }, { type: "patch", label: "CREST CONSTRUCTION" }, { type: "wall", label: "HOME FIELD LANGUAGE" }, { type: "jersey", label: "UNIFORM GRID", detail: "W" }] },
      { number: "05", title: "Applications", label: "Featured Case Study", heading: "Westhaven University", category: "Applications / Built To Show Up Everywhere", paragraph: "Every application was tested for distance, movement, reproduction, and the pace of modern athletic communications.", stats: [{ value: "100+", label: "Applications" }, { value: "17", label: "Sport Kits" }, { value: "6", label: "Facility Zones" }], images: [{ type: "jersey", label: "WESTHAVEN", detail: "24" }, { type: "wall", label: "TRADITION BUILT HERE" }, { type: "flag", label: "W" }, { type: "book", label: "APPLICATION STANDARDS" }] },
      { number: "06", title: "Results", label: "Featured Case Study", heading: "Westhaven University", category: "Results / A Unified Athletic Presence", paragraph: "The finished identity gives every team a shared visual language while preserving the confidence, tradition, and scale of the program.", stats: [{ value: "1", label: "Shared System" }, { value: "17", label: "Teams Aligned" }, { value: "2026", label: "Launch Season" }], images: [{ type: "flag", label: "W" }, { type: "wall", label: "WESTHAVEN ATHLETICS" }, { type: "jersey", label: "WESTHAVEN", detail: "01" }, { type: "book", label: "FINAL IDENTITY KIT" }] },
    ],
  },
  selectedWork: {
    sectionTitle: "Selected Work",
    viewAllLabel: "View Selected Work",
    viewAllUrl: "/work",
    items: ["panthers-football", "westhaven-university", "cardinals-baseball", "ironwood-high-school"],
  },
  testimonials: {
    label: "TESTIMONIALS",
    headline: "TRUSTED BY TEAMS, BRANDS, AND CREATORS",
    supportingCopy: "Words from clients, collaborators, and organizations I’ve worked with across identity, mascot, typography, and brand systems.",
    items: [
      { id: "ozone", quote: "Been working with Athaya since early 2019 and never been disappointed or let down. Always working to get you exactly what we are looking for, fast and reliable while being able to work to a tight schedule. Sends you updates during the design phase so you can make changes if required. Would highly recommend working with Athaya.", name: "Ozone Group Branding", role: "CEO", organization: "Ozone Group LLC", category: "Brand Identity", logo: "/uploads/testimonials/ozone-group-logo-white.png", featured: true, order: 1 },
      { id: "athletic-program", quote: "Athaya has been nothing short of AMAZING! He is the most skilled and Professional person i've ever had the pleasure of doing business with. I admire his communication and just how he kept me in the loop with how the project was going as he worked on my logo. Athaya will ALWAYS have my love and support.. This man is a W!", name: "Achillies Arcadian", role: "Online Content Creator", organization: "Self Employed", category: "Mascot design", logo: "/uploads/testimonials/achilies-arcadian-logo-white.png", featured: true, order: 2 },
      { id: "creator-brand", quote: "Athaya has been nothing short of AMAZING! He is the most skilled and Professional person i've ever had the pleasure of doing business with. I admire his communication and just how he kept me in the loop with how the project was going as he worked on my logo. Athaya will ALWAYS have my love and support.. This man is a W!", name: "PowerGotNow", role: "Gaming Clan Leader, Online Content Creator", organization: "DF Clan", category: "Brand Identity", logo: "/uploads/testimonials/powergotnow-logo.png", featured: true, order: 3 },
      { id: "agency-collaboration", quote: "I loved working with Athaya. He were incredibly receptive of any idea I had and also offered your own experience and expertise on how to improve those ideas. There is no doubt in my mind that we will work together again in the future.", name: "Dylan \"Dilly\"", role: "Team Leader", organization: "RIOT Paintball Team", category: "Identity Mark", logo: "/uploads/testimonials/dylan-dilly-logo.png", featured: true, order: 4 },
    ],
    logos: [
      { id: "ozone", name: "Ozone Group LLC", logo: "/uploads/testimonials/ozone-group-logo-white.png", alt: "Ozone Group LLC logo", order: 1 },
      { id: "athletic-program", name: "Achillies Arcadian", logo: "/uploads/testimonials/achilies-arcadian-logo-white.png", alt: "Achillies Arcadian logo", order: 2 },
      { id: "creator-brand", name: "PowerGotNow", logo: "/uploads/testimonials/powergotnow-logo.png", alt: "PowerGotNow logo", order: 3 },
      { id: "agency-collaboration", name: "Dylan Dilly", logo: "/uploads/testimonials/dylan-dilly-logo.png", alt: "Dylan Dilly logo", order: 4 },
    ],
  },
  approach: {
    label: "Process",
    headline: "Character.\nCraft. Presence.",
    paragraph: "Athaya Designed creates marks and identity systems with clear structure, polished craft, and enough character to feel recognizable across apparel, signage, social media, and long-term brand use.",
    ctaLabel: "About The Practice",
    ctaUrl: "/about",
    images: [
      "/uploads/images/cloud-1782386837010.jpeg",
      "/projects/project 2/Hero.webp",
      fallbackImages.football,
      fallbackImages.facility,
    ],
  },
  footerCta: {
    headline: "Let's Build An Identity\nWith Character.",
    paragraph: "Tell me about your team, school, community, or brand and let's create an identity that feels established, recognizable, and built to last.",
    ctaLabel: "Start a Project",
    ctaUrl: "/contact",
  },
};

export const defaultAboutContent = {
  pageLabel: "About ATHAYA DESIGNED",
  headline: "Independent Identity Design Practice",
  supportingCopy: "Character-driven identity design for teams, schools, and brands.",
  heroImage: "/uploads/backgrounds/about-story-hero.jpg",
  backgroundImage: "",
  studioPositioningCopy: "Athaya Designed is the personal design practice of Ahmad Athaya Nurhani, an identity designer specializing in athletic branding, mascot logos, lettermarks, and visual identity systems. Built from years inside gaming, sports, and creative communities, Athaya Designed focuses on creating marks that feel distinctive, polished, and made to represent something bigger than just a logo.",
  founderNoteLabel: "About The Designer",
  founderNoteHeadline: "A personal practice shaped by gaming, sports, creative communities, and polished identity systems.",
  founderNoteParagraphs: [
    "From gaming and sports communities to polished identity systems for teams, schools, communities, and brands, the practice keeps the bold character of that early work while giving it stronger structure and presentation.",
    "The practice is focused on marks with character, craft, presence, and structure: logos, mascots, lettermarks, athletic identities, and brand tools that feel distinctive and built for long-term use.",
  ],
  storyLabel: "Personal Story",
  storyHeadline: "Built from gaming, sports, and creative communities into a focused identity practice.",
  storyParagraphs: [
    "Before ATHAYA DESIGNED became a studio practice, the work started inside the worlds that shaped how I see identity: gaming communities, sports culture, custom graphics, team pride, and the visual language people use to represent who they are.",
    "That background still drives the work today. I care about marks that feel personal, competitive, polished, and useful. A logo should not only look strong in a presentation; it should work on apparel, avatars, social graphics, signage, and every real place where a team, creator, school, or brand needs to show up.",
    "ATHAYA DESIGNED is my way of building those identities with more structure: combining character, typography, strategy, and practical systems so each project can feel distinctive now and still hold up over time.",
  ],
  beliefPrinciples: [
    { number: "01", title: "Character", description: "A strong identity should carry a clear point of view." },
    { number: "02", title: "Craft", description: "Every mark should be built with detail, discipline, and intention." },
    { number: "03", title: "Presence", description: "A good identity should hold up across every environment." },
    { number: "04", title: "Structure", description: "A complete system makes the identity easier to use, scale, and protect." },
  ],
  whoWeHelp: ["Teams", "Schools", "Communities", "Athletic Programs", "Clubs", "Brands", "Online Creators"],
  studioFocus: ["Identity Marks", "Mascot Identities", "Lettermarks & Brandmarks", "Athletic Branding", "Brand Strategies", "Typography", "Visual Identity Systems", "Brand Guidelines"],
  ctaHeadline: "Build A Mark With Character And Presence.",
  primaryCtaLabel: "View Selected Work",
  primaryCtaUrl: "/work",
  secondaryCtaLabel: "BOOK A DISCOVERY CALL",
  secondaryCtaUrl: "https://calendly.com/athayadzn/30min",
};

export const defaultContactContent = {
  pageLabel: "Contact",
  headline: "Start a Project",
  supportingCopy: "Tell me about your team, school, brand, or identity project. I will review the details and follow up with the best next step.",
  backgroundImage: "",
  bookingUrl: "https://calendly.com/athayadzn/30min",
  email: "hello@athayadesigned.com",
  responseTime: "Usually within 1-2 business days.",
  contactOptions: [{ label: "Email Studio", url: "mailto:hello@athayadesigned.com" }],
  typicalProjects: ["Identity Marks", "Wordmarks & Brandmarks", "Mascot & Character Identities", "Athletic & School Branding", "Brand Strategies", "Brand Guidelines", "Visual Identity Systems"],
  formEnabled: true,
  formSubmissionMode: "mailto",
  formEndpointUrl: "",
  formFields: [
    { label: "Name", name: "name", type: "text", required: true, options: [], enabled: true, order: 1 },
    { label: "Email", name: "email", type: "email", required: true, options: [], enabled: true, order: 2 },
    { label: "Organization / Team / School", name: "organization", type: "text", required: false, options: [], enabled: true, order: 3 },
    { label: "Project Type", name: "projectType", type: "select", required: true, options: ["Identity Mark", "Mascot / Character Identity", "Athletic & School Branding", "Brand Guidelines", "Full Identity System", "Other"], enabled: true, order: 4 },
    { label: "Budget Range", name: "budget", type: "select", required: false, options: ["$750-$1,500", "$1,500-$2,500", "$2,500-$5,000", "$5,000+", "Not sure yet"], enabled: true, order: 5 },
    { label: "Timeline", name: "timeline", type: "text", required: false, options: [], enabled: true, order: 6 },
    { label: "Project Details", name: "details", type: "textarea", required: true, options: [], enabled: true, order: 7 },
  ],
};

export const defaultSEOContent = {
  pages: {
    home: { title: "ATHAYA DESIGNED - Sports Identity & Mascot Logo Design Studio", description: "ATHAYA DESIGNED creates mascot logos, athletic identity systems, school branding, apparel applications, and complete visual identity systems for teams, schools, communities, and sports brands.", canonicalUrl: "/", ogImage: "/assets/athaya-brandmark.png", twitterImage: "/assets/athaya-brandmark.png", keywords: "identity design, mascot logo, athletic branding, school branding, logo design", jsonLdType: "ProfessionalService", noIndex: false },
    work: { title: "Selected Work - Sports Identity, Mascot Logos & Athletic Branding | ATHAYA DESIGNED", description: "Explore selected identity work by ATHAYA DESIGNED, including mascot logos, athletic marks, lettermarks, typography, apparel applications, and visual systems for teams, schools, and brands.", canonicalUrl: "/work", ogImage: "/assets/athaya-brandmark.png", twitterImage: "/assets/athaya-brandmark.png", keywords: "", jsonLdType: "CreativeWork", noIndex: false },
    fonts: { title: "ATHAYA DESIGNED Fonts - Display Typefaces for Sports Brands", description: "Explore ATHAYA DESIGNED display fonts, sports-inspired typefaces, and lettering systems for sports branding, apparel graphics, team identities, and visual systems.", canonicalUrl: "/fonts", ogImage: "/assets/athaya-brandmark.png", twitterImage: "/assets/athaya-brandmark.png", keywords: "", jsonLdType: "Product", noIndex: false },
    services: { title: "Services - Mascot Logo, Athletic Identity & School Branding", description: "Premium identity design services for teams, schools, clubs, creators, and brands, including mascot marks, athletic identity systems, school branding, lettermarks, apparel applications, and brand guidelines.", canonicalUrl: "/services", ogImage: "/assets/athaya-brandmark.png", twitterImage: "/assets/athaya-brandmark.png", keywords: "", jsonLdType: "ProfessionalService", noIndex: false },
    about: { title: "About ATHAYA DESIGNED - Independent Sports Identity Designer", description: "Learn about ATHAYA DESIGNED, the independent identity design practice of Ahmad Athaya Nurhani, focused on character-driven marks, mascot identities, athletic branding, and visual systems.", canonicalUrl: "/about", ogImage: "/assets/athaya-brandmark.png", twitterImage: "/assets/athaya-brandmark.png", keywords: "", jsonLdType: "Organization", noIndex: false },
    contact: { title: "Start a Project - ATHAYA DESIGNED", description: "Start a project with ATHAYA DESIGNED for mascot logo design, athletic identity systems, school branding, lettermarks, or complete identity work.", canonicalUrl: "/contact", ogImage: "/assets/athaya-brandmark.png", twitterImage: "/assets/athaya-brandmark.png", keywords: "", jsonLdType: "ProfessionalService", noIndex: false },
  },
  workDetails: {},
  fontDetails: {},
};

export const defaultAssetsContent = {
  assets: [],
};

export const defaultContentBundle = {
  site: defaultSiteContent,
  home: defaultHomeContent,
  works: defaultWorks,
  fonts: defaultFonts,
  services: defaultServicesContent,
  about: defaultAboutContent,
  contact: defaultContactContent,
  seo: defaultSEOContent,
  assets: defaultAssetsContent,
};
